Add support for bluetooth presentment
spruceid/wallet-sdk-kt pull request #2
Opened 2024-02-28 16:30 UTC by w4ll3

2024-03-01 17:15 UTC, tristanmiller-spruceid commented
I created a task to cover some cleanup tasks, but we should get this in and starting to use it with react-native.

2024-03-01 17:15 UTC, tristanmiller-spruceid approved these changes

2024-03-05 14:13 UTC, sbihel requested changes
Maybe it's due to the move to maven central but when I tested it it didn't get past the qr code -- and from the logs there doesn't seem to be any activity past "start scanning". Does it work for you locally?

2024-03-05 14:13 UTC, sbihel commented on WalletSdk/src/main/java/com/spruceid/walletandroidsdk/BleCentral.kt
> +package com.spruceid.walletandroidsdk
To be consistent with the other libraries I think it should be `com.spruceid.wallet.sdk:walletsdk`

2024-03-06 10:48 UTC, sbihel commented
I had simply denied the "Discover Nearby Devices" permission 🤦

2024-03-06 10:49 UTC, sbihel approved these changes

2024-03-06 10:55 UTC, merged